In [144]:
import numpy as np

In [145]:
# load models
from keras.models import load_model
from keras.preprocessing.image import ImageDataGenerator
model1 = load_model('model1.h5')
model2 = load_model('model2.h5')
model3 = load_model('model3.h5')
model4 = load_model('model4.h5')

In [146]:
train_datagen = ImageDataGenerator(rescale=1./255,
                                      shear_range=0.2, 
                                        zoom_range=0.2,
                                        horizontal_flip=True)
train_set = train_datagen.flow_from_directory(
        'dataset/train',
        target_size = (32,32),
        color_mode="grayscale",
        batch_size=4,
        class_mode='binary'
        )

Found 30 images belonging to 2 classes.


In [147]:
test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(32,32),
        batch_size=4,
        color_mode="grayscale",
        class_mode='binary')

Found 30 images belonging to 2 classes.


In [148]:
models = [model1, model2, model3, model4]

In [149]:
preds = [model.predict(train_set) for model in models]

In [150]:
preds = np.array(preds)
preds

array([[[1.13362372e-02],
        [2.06147134e-02],
        [9.71921325e-01],
        [9.85933423e-01],
        [6.62171841e-03],
        [9.86170411e-01],
        [2.37840414e-03],
        [2.88789868e-02],
        [9.89944458e-01],
        [9.94513333e-01],
        [6.46749139e-03],
        [5.10290265e-02],
        [9.99452233e-01],
        [1.90866411e-01],
        [9.99993443e-01],
        [5.78065276e-01],
        [7.52870679e-01],
        [6.91910088e-02],
        [9.57039714e-01],
        [2.58350372e-03],
        [4.29484248e-02],
        [9.89172995e-01],
        [5.81751764e-01],
        [3.41568291e-02],
        [3.32948075e-05],
        [9.79447126e-01],
        [8.72605979e-01],
        [9.98394847e-01],
        [9.20452833e-01],
        [9.39731479e-01]],

       [[4.99561131e-01],
        [4.99575198e-01],
        [4.99572098e-01],
        [4.99574214e-01],
        [4.99573737e-01],
        [4.99468029e-01],
        [4.99572545e-01],
        [4.99576092e-01],
        [4

In [151]:
summed = np.sum(preds, axis=0)
summed

array([[1.8379364 ],
       [0.6769486 ],
       [3.4362273 ],
       [1.9136857 ],
       [1.4019758 ],
       [3.413704  ],
       [1.3125021 ],
       [2.4066348 ],
       [1.9278854 ],
       [1.6097693 ],
       [0.61370564],
       [1.3024731 ],
       [2.1460218 ],
       [1.7171141 ],
       [1.6651473 ],
       [2.08094   ],
       [2.1945815 ],
       [1.4615955 ],
       [3.0005934 ],
       [2.2531998 ],
       [1.4081383 ],
       [2.002806  ],
       [1.0969675 ],
       [2.3593018 ],
       [1.7022016 ],
       [3.4448977 ],
       [2.8377554 ],
       [3.4276836 ],
       [2.8873124 ],
       [1.8140703 ]], dtype=float32)

In [159]:
ensemble_preds = np.argmax(summed, axis=1)
print(ensemble_preds)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [153]:
prediction1 = (model1.predict(train_set) > 0.5).astype("int32")
prediction2 = (model2.predict(train_set) > 0.5).astype("int32")
prediction3 = (model3.predict(train_set) > 0.5).astype("int32")
prediction4 = (model4.predict(train_set) > 0.5).astype("int32")

In [154]:
from sklearn.metrics import accuracy_score
print(accuracy_score(test_set.classes, prediction1))
print(accuracy_score(test_set.classes, prediction2))
print(accuracy_score(test_set.classes, prediction3))
print(accuracy_score(test_set.classes, prediction4))
print(accuracy_score(test_set.classes, ensemble_preds))

0.7
0.5
0.5666666666666667
0.5666666666666667
0.5


In [155]:
models = [model1, model2, model3,model4]
preds = [model.predict(train_set) for model in models]
preds=np.array(preds)
weights = [0.4, 0.2, 0.1, 0.3]
weighted_preds = np.tensordot(preds,weights, axes=((0),(0)))
weighted_preds

array([[0.19618   ],
       [0.45151756],
       [0.39639074],
       [0.78331729],
       [0.5177885 ],
       [0.52346882],
       [0.4394799 ],
       [0.59030333],
       [0.21465393],
       [0.40748954],
       [0.39491612],
       [0.84135665],
       [0.51242794],
       [0.41877109],
       [0.16927108],
       [0.6410964 ],
       [0.19913093],
       [0.8803726 ],
       [0.12145235],
       [0.584644  ],
       [0.84001906],
       [0.56367851],
       [0.8020253 ],
       [0.47780964],
       [0.47285474],
       [0.49024423],
       [0.52803476],
       [0.65655567],
       [0.48336105],
       [0.23649257]])

In [156]:
weighted_ensemble_prediction = np.argmax(weighted_preds, axis=1)
print(weighted_ensemble_prediction)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [157]:
weighted_accuracy = accuracy_score(train_set.classes, weighted_ensemble_prediction)
print(train_set.classes)
weighted_accuracy

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


0.5